services:
  - type: web
    name: jetset-app
    env: node
    buildCommand: |
      npm install
      mkdir -p resources/js/Pages resources/js/Pages/Auth
      cp -r resources/js/pages/* resources/js/Pages/
      cp -r resources/js/pages/Auth/* resources/js/Pages/Auth/
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: DB_DATABASE
        value: /data/database.sqlite
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: new-app-db
    plan: free
    databaseName: new_app
    user: new_app_user
