services:
  - type: web
    name: jetset-app
    env: node
    buildCommand: |
      # Print debug info
      echo "Current directory: $(pwd)"
      ls -la resources/js
      # Create Pages directory and copy files
      mkdir -p resources/js/Pages resources/js/Pages/Auth
      cp -r resources/js/pages/* resources/js/Pages/
      # Replace import statements in app.jsx
      sed -i 's/from ".\/pages\//from ".\/Pages\//g' resources/js/app.jsx
      # Install dependencies and build
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: DB_DATABASE
        value: /data/database.sqlite
      - key: VITE_API_URL
        value: /api
      - key: VITE_APP_NAME
        value: "JetSet App"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: new-app-db
    plan: free
    databaseName: new_app
    user: new_app_user
