services:
  - type: web
    name: jetset
    env: node
    region: singapore
    plan: free
    runtime: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: new-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: new-app-db
          property: connectionString
      - key: NODE_VERSION
        value: 20.x

databases:
  - name: new-app-db
    plan: free
    databaseName: new_app
    user: new_app_user
